Add RSCT Validate/Repair check in ServiceReport tool
linux-ras/ServiceReport pull request #15
Opened 2020-08-17 06:40 UTC by seeteena

Signed-off-by: Seeteena Thoufeek s1seetee@linux.vnet.ibm.com

2020-08-18 09:32 UTC, sourabhjains commented
Hello @seeteena 

Merged your pull request to the next branch.
https://github.com/linux-ras/ServiceReport/commit/fbe9530b2d24452379028a21a9d612923c6a40ea

Thanks for your contribution.

- Sourabh Jain

2020-08-18 09:56 UTC, hegdevasant commented
When I run this I see ;

servicereport 2.2.2

RSCT configuration check                            FAIL

  IBM Power Repo Package check                      FAIL     Manual Fix Needed install ibm-power-repo package, run /opt/ibm/lop/configure to agree with the license

<-- Mix of upper and small case is not nice! Probably this should be added at the end .. 
Also it doesn't describe how to get `ibm-power-repo` package . Remember its not shipped by distros 



  RSCT Installation path                            FAIL
  RSCT package check                                FAIL
  RSCT service status                               FAIL

-Vasant

2020-08-18 10:43 UTC, sourabhjains commented
Thanks for the review @hegdevasant

Will add instructions to install ibm-power-repo package.

- Sourabh Jain

2024-09-10 06:20 UTC, sourabhjains commented
Any update on this pull request?

2025-10-31 07:19 UTC, sourabhjains requested changes

2025-10-31 07:19 UTC, sourabhjains commented on servicereportpkg/validate/plugins/rsct.py
> +        """IBM Power Repo Package Check"""
Consider renaming the function to a name that is more closely associated with the package check it is performing, as the current function name does not align with its intended purpose.

2025-10-31 07:19 UTC, sourabhjains commented on servicereportpkg/validate/plugins/rsct.py
> +    def get_subsystem_status(self, subsystem):
Adding rsct in the function makes it more meaning full.

2025-10-31 07:19 UTC, sourabhjains commented on servicereportpkg/validate/plugins/rsct.py
> +                subsys_list.append((subsystem, subsys_status))
Let's have only one subsys_list.append call. Take it out from if and else.

The same goes for the RSCT package check.

2025-10-31 07:19 UTC, sourabhjains commented on servicereportpkg/validate/plugins/rsct.py
> +class RSCT(Plugin, PSeriesScheme):
I hope that no changes are required if this plugin is executed on different distributions.

2025-10-31 07:19 UTC, sourabhjains commented on servicereportpkg/repair/plugins/rsct_repair.py
> +
Consider adding RSCT full form at least once in the plugin and commit message.

2025-10-31 07:19 UTC, sourabhjains commented on servicereportpkg/repair/plugins/rsct_repair.py
> +for more details")
Let's have a variable to store the above string.

2026-06-15 05:04 UTC, closed without merging